import { create } from 'zustand'
import { devtools } from "zustand/middleware";
import { IUsers } from "../../types/Types";


export const useUsers = create<IUsers>()(devtools((set) => ({
    users: {
        list: [
            {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "123-456-7890",
            address: '',
            // {
            //     number: "123",
            //     street: "Main Street",
            //     apt: "Apt 4B",
            //     city: "New York",
            //     state: "NY",
            //     country: "USA",
            //     postalCode: "10001",
            // },
            status: "Active",
            title: "Software Engineer",
            jobDescription: "Front-end development",
            compensation: "$80,000 per year",
            paymentMethod: "Direct Deposit",
            compensationPeriod: "Monthly",
            agreementSigned: "2023-01-15",
            manager: "Alice Smith",
            lastPaymentDate: "2023-10-15",
            signedConfidentiallyAgreement: "2023-01-10",
            workAgreements: "Full-time, 40 hours per week",
            GovtID: "123-45-6789",
            TimeSheetsSubmitted: "2023-10-25",
            ConfirmReceiptPaid: "2023-10-28",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "987-654-3210",
            address: '',
            // {
            //     number: "456",
            //     street: "Oak Avenue",
            //     apt: "Apt 2C",
            //     city: "Los Angeles",
            //     state: "CA",
            //     country: "USA",
            //     postalCode: "90001",
            // },
            status: "Inactive",
            title: "Graphic Designer",
            jobDescription: "Print and digital design",
            compensation: "$60,000 per year",
            paymentMethod: "Check",
            compensationPeriod: "Bi-weekly",
            agreementSigned: "2023-02-20",
            manager: "Bob Johnson",
            lastPaymentDate: "2023-10-20",
            signedConfidentiallyAgreement: "2023-02-15",
            workAgreements: "Part-time, 20 hours per week",
            GovtID: "987-65-4321",
            TimeSheetsSubmitted: "2023-10-25",
            ConfirmReceiptPaid: "2023-10-28",
        },
        {
            id: 3,
            name: "Alice Brown",
            email: "alice@example.com",
            phone: "555-555-5555",
            address: '',
            // {
            //     number: "789",
            //     street: "Pine Street",
            //     apt: "Apt 1A",
            //     city: "Chicago",
            //     state: "IL",
            //     country: "USA",
            //     postalCode: "60601",
            // },
            status: "Active",
            title: "Marketing Manager",
            jobDescription: "Marketing strategy and campaigns",
            compensation: "$90,000 per year",
            paymentMethod: "PayPal",
            compensationPeriod: "Bi-monthly",
            agreementSigned: "2023-03-10",
            manager: "Eve Wilson",
            lastPaymentDate: "2023-10-23",
            signedConfidentiallyAgreement: "2023-03-05",
            workAgreements: "Full-time, 45 hours per week",
            GovtID: "789-12-3456",
            TimeSheetsSubmitted: "2023-10-26",
            ConfirmReceiptPaid: "2023-10-29",
        },
        {
            id: 4,
            name: "David Johnson",
            email: "david@example.com",
            phone: "444-123-7890",
            address: '',
            // {
            //     number: "246",
            //     street: "Cedar Road",
            //     apt: "Apt 3D",
            //     city: "San Francisco",
            //     state: "CA",
            //     country: "USA",
            //     postalCode: "94101",
            // },
            status: "Active",
            title: "Product Manager",
            jobDescription: "Product development and strategy",
            compensation: "$100,000 per year",
            paymentMethod: "Bank Transfer",
            compensationPeriod: "Monthly",
            agreementSigned: "2023-01-05",
            manager: "Sarah Clark",
            lastPaymentDate: "2023-10-18",
            signedConfidentiallyAgreement: "2023-01-01",
            workAgreements: "Full-time, 40 hours per week",
            GovtID: "246-80-1357",
            TimeSheetsSubmitted: "2023-10-24",
            ConfirmReceiptPaid: "2023-10-27",
        },
        {
            id: 5,
            name: "Eve Wilson",
            email: "eve@example.com",
            phone: "777-888-9999",
            address: '',
            // {
            //     number: "101",
            //     street: "Maple Avenue",
            //     apt: "Apt 2A",
            //     city: "Boston",
            //     state: "MA",
            //     country: "USA",
            //     postalCode: "02101",
            // },
            status: "Active",
            title: "HR Specialist",
            jobDescription: "Human resources and recruitment",
            compensation: "$70,000 per year",
            paymentMethod: "Check",
            compensationPeriod: "Bi-weekly",
            agreementSigned: "2023-02-25",
            manager: "Bob Johnson",
            lastPaymentDate: "2023-10-22",
            signedConfidentiallyAgreement: "2023-02-20",
            workAgreements: "Full-time, 40 hours per week",
            GovtID: "101-22-3333",
            TimeSheetsSubmitted: "2023-10-25",
            ConfirmReceiptPaid: "2023-10-28",
        },
        // {
        //     id: 6,
        //     name: "Sarah Clark",
        //     email: "sarah@example.com",
        //     phone: "888-444-7777",
        //     address: {
        //         number: "567",
        //         street: "Cherry Lane",
        //         apt: "Apt 3B",
        //         city: "Seattle",
        //         state: "WA",
        //         country: "USA",
        //         postalCode: "98101",
        //     },
        //     status: "Active",
        //     title: "Data Scientist",
        //     jobDescription: "Data analysis and machine learning",
        //     compensation: "$95,000 per year",
        //     paymentMethod: "Direct Deposit",
        //     compensationPeriod: "Monthly",
        //     agreementSigned: "2023-01-30",
        //     manager: "John Doe",
        //     lastPaymentDate: "2023-10-18",
        //     signedConfidentiallyAgreement: "2023-01-25",
        //     workAgreements: "Full-time, 40 hours per week",
        //     GovtID: "567-90-1234",
        //     TimeSheetsSubmitted: "2023-10-23",
        //     ConfirmReceiptPaid: "2023-10-27",
        // },
        // {
        //     id: 7,
        //     name: "Bob Johnson",
        //     email: "bob@example.com",
        //     phone: "333-111-9999",
        //     address: {
        //         number: "789",
        //         street: "Pine Street",
        //         apt: "Apt 2C",
        //         city: "Austin",
        //         state: "TX",
        //         country: "USA",
        //         postalCode: "78701",
        //     },
        //     status: "Active",
        //     title: "Sales Manager",
        //     jobDescription: "Sales team management",
        //     compensation: "$85,000 per year",
        //     paymentMethod: "PayPal",
        //     compensationPeriod: "Bi-monthly",
        //     agreementSigned: "2023-03-05",
        //     manager: "Alice Smith",
        //     lastPaymentDate: "2023-10-21",
        //     signedConfidentiallyAgreement: "2023-03-01",
        //     workAgreements: "Full-time, 45 hours per week",
        //     GovtID: "789-34-5678",
        //     TimeSheetsSubmitted: "2023-10-25",
        //     ConfirmReceiptPaid: "2023-10-29",
        // },
        // {
        //     id: 8,
        //     name: "Mary White",
        //     email: "mary@example.com",
        //     phone: "666-333-2222",
        //     address: {
        //         number: "333",
        //         street: "Elm Street",
        //         apt: "Apt 1D",
        //         city: "Denver",
        //         state: "CO",
        //         country: "USA",
        //         postalCode: "80201",
        //     },
        //     status: "Active",
        //     title: "Accountant",
        //     jobDescription: "Financial accounting and reporting",
        //     compensation: "$75,000 per year",
        //     paymentMethod: "Bank Transfer",
        //     compensationPeriod: "Monthly",
        //     agreementSigned: "2023-01-20",
        //     manager: "David Johnson",
        //     lastPaymentDate: "2023-10-20",
        //     signedConfidentiallyAgreement: "2023-01-15",
        //     workAgreements: "Full-time, 40 hours per week",
        //     GovtID: "333-55-7777",
        //     TimeSheetsSubmitted: "2023-10-24",
        //     ConfirmReceiptPaid: "2023-10-27",
        // },
        // {
        //     id: 9,
        //     name: "Olivia Green",
        //     email: "olivia@example.com",
        //     phone: "222-888-7777",
        //     address: {
        //         number: "987",
        //         street: "Cypress Lane",
        //         apt: "Apt 3A",
        //         city: "San Diego",
        //         state: "CA",
        //         country: "USA",
        //         postalCode: "92101",
        //     },
        //     status: "Active",
        //     title: "Customer Support Specialist",
        //     jobDescription: "Customer inquiries and support",
        //     compensation: "$55,000 per year",
        //     paymentMethod: "Direct Deposit",
        //     compensationPeriod: "Monthly",
        //     agreementSigned: "2023-01-25",
        //     manager: "Eve Wilson",
        //     lastPaymentDate: "2023-10-17",
        //     signedConfidentiallyAgreement: "2023-01-20",
        //     workAgreements: "Full-time, 40 hours per week",
        //     GovtID: "987-12-3456",
        //     TimeSheetsSubmitted: "2023-10-23",
        //     ConfirmReceiptPaid: "2023-10-26",
        // },
        // {
        //     id: 10,
        //     name: "Michael Adams",
        //     email: "michael@example.com",
        //     phone: "777-555-6666",
        //     address: {
        //         number: "555",
        //         street: "Sycamore Road",
        //         apt: "Apt 4C",
        //         city: "Miami",
        //         state: "FL",
        //         country: "USA",
        //         postalCode: "33101",
        //     },
        //     status: "Active",
        //     title: "Quality Assurance Tester",
        //     jobDescription: "Software testing and quality assurance",
        //     compensation: "$70,000 per year",
        //     paymentMethod: "Check",
        //     compensationPeriod: "Bi-weekly",
        //     agreementSigned: "2023-02-10",
        //     manager: "Sarah Clark",
        //     lastPaymentDate: "2023-10-19",
        //     signedConfidentiallyAgreement: "2023-02-05",
        //     workAgreements: "Full-time, 40 hours per week",
        //     GovtID: "555-89-1234",
        //     TimeSheetsSubmitted: "2023-10-24",
        //     ConfirmReceiptPaid: "2023-10-28",
        // },

        ],
    },
    setUsers: (data) => set((state) => ({ users: { ...state.users, list: data } })),
    addUser: (data) => set((state) => (
        { users: { ...state.users, list: [data, ...state.users.list] } }
    )),

    editUser: (data) => set((state) => (
        { users: { ...state.users, list: [...state.users.list.map(item => item.id === data.id ? data : item)] } }
    )),
    removeUser: (data) => set((state) => ({
        users: {
            ...state.users, list: [
                ...state.users.list.filter(item => item.id !== data)
            ]
        }
    })),
})))


