import { NavLink } from 'react-router-dom';

const Index = () => {
    return (
        <div className='bg-[#698bbb] text-white w-full h-full flex flex-col items-center py-10'>
            <NavLink to={'/'} className=" text-[#94bcf5] text-lg uppercase font-bold self-start ml-[10%]">Propel Inc.</NavLink>
            <h1 className='text-7xl font-semibold mb-10'>Legal Notices</h1>
            <p className="w-4/5 text-justify text-xl font-light tracking-wider leading-9 mb-14">
                This Terms of Use (this “Terms of Use”) is agreed to Propel Inc., on behalf of its subsidiaries and divisions (collectively, “Propel”) and you, or if you represent an entity or other organization, that entity or organization (in either case, “you”).
                <br />
                <br />
                Propel offers end users (“Users”) the ability to access information, data, and other content (“Content”), as well as online product review information, event registration, User collaboration features, and other interactive functionality and services (“Services”) available through Propel’s online platform (the “Platform”).
                <br />
                <br />
                You may access the Platform through the website located at https://www.Propelem.com/, and any other websites operated by Propel or its subsidiaries and divisions (each, a “Site”) or using mobile applications provided by and on behalf of Propel or its subsidiaries and divisions (each, an “Application,” and each Site and Application treated as a part of the “Platform” for purposes of this Terms of Use). This Terms of Use applies to your use of and access to the Platform and the Content and Services available through the Platform.
                <br />
                <br />
                This Terms of Use includes the terms and conditions below and the Privacy Policy, located at https://www.Propelem.com/legal (“Privacy Policy”) relating to the Platform. You are responsible for compliance with this Terms of Use (including the Privacy Policy).
                <br /><br /><br /><br /><br />
                Unless you later enter into any other agreements with Propel regarding the Platform or any Content or Services, this Terms of Use is the complete and exclusive agreement between you and Propel regarding your access to and use of the Platform and all Content and Services. This Terms of Use supersedes any prior agreement or other communications between you and Propel relating to your use of and access to the Platform and any Content or Services.
                <br /><br />
                PLEASE CAREFULLY READ THIS TERMS OF USE. BY ACCESSING OR USING THE PLATFORM OR ANY CONTENT OR SERVICES, OR BY CLICKING A BOX THAT STATES THAT YOU ACCEPT OR AGREE TO THIS TERMS OF USE, YOU AGREE THAT YOU HAVE READ AND AGREE TO BE BOUND BY THIS TERMS OF USE.
                <br /><br />
                IF YOU DO NOT AGREE TO THIS TERMS OF USE, OR DO NOT MEET THE QUALIFICATIONS INCLUDED IN THIS TERMS OF USE, PROPEL IS NOT WILLING TO PROVIDE YOU WITH ACCESS TO OR USE OF THE PLATFORM OR ANY CONTENT OR SERVICES ACCESSIBLE THROUGH THE PLATFORM AND YOU MUST NOT ACCESS OR USE THE PLATFORM OR ANY CONTENT OR SERVICES. IF YOU ACCESS OR USE THE PLATFORM OR ANY CONTENT OR SERVICES, YOU ACKNOWLEDGE THAT YOU MEET THE QUALIFICATIONS INCLUDED IN THIS TERMS OF USE AND AGREE TO BE BOUND BY THIS TERMS OF USE.
                <br /><br />
                <br />
                1. DEFINITIONS. Terms used in this Terms of Use have the definitions given in this Terms of Use or, if not defined in this Terms of Use, have their plain English meaning as commonly interpreted in the United States, even if Propel provides a translated version of this Terms of Use. To the extent any ambiguity or inconsistency exists between the English version of this Terms of Use and a version in any other language, the English (as interpreted in the United States) version of the Terms of Use controls.
                <br /><br />
                <br />
                2.              TERM. This Terms of Use is entered into as of the earlier of the date you first access or use the Platform or any Content or Services (the "Effective Date") and will continue until terminated as set forth herein.
                <br /><br />
                <br />
                3.             MODIFICATIONS. Propel reserves the right, at any time, to modify the Platform or any Content or Services, with or without notice to you, by making those modifications available on the Platform. Propel also reserves the right, at any time, to modify this Terms of Use. Propel will inform you of the presence of any changes to this Terms of Use by posting those changes on the Platform or by providing you with notice through the Platform. Any modifications will be effective immediately upon posting on the Platform or delivery of such notice through the Platform. You may terminate this Terms of Use as set forth below if you object to any such modifications. However, you will be deemed to have agreed to any and all modifications through your continued use of the Platform or any Content or Services following such notice period.
                <br /><br />
                <br />
                4.              ELIGIBILITY.    The Platform, Content, and Services are intended for use by individuals 13 years of age and older. If you are a parent or guardian of a child under 13, then you may allow your child to access the Platform, Content, or Services only under your direct supervision. You will not allow your child to access the Platform, Content, or Services other than under your direct supervision and you will be solely responsible for all access to and use of the Platform, Content, or Services by your child. If you are 13 or older but younger than 18, then you may access and use the Platform, Content, and Services only if your parent or guardian accepts this Terms and Use on your behalf. If you are a parent or guardian agreeing to this Terms of Use for the benefit of a child age 13 or older but under 18, then you agree you will be solely responsible for all access to and use of the Platform, Content, or Services.
                <br /><br />
                <br />
                5.              ACCOUNT.
                <br /><br />
                5.1.          Users. You are permitted to access certain Content and Services without establishing a user account on the Platform, provided that you have agreed to this Terms of Use. However, access to and use of certain Content and Services may require that you establish a user account (an “Account”) on the Platform. Approval of your request to establish an Account will be at the sole discretion of Propel. If you are an organization, you may authorize designated employees within your organization to use and access the Platform, Content, and Services on your behalf through your Account (you and each such individual, as applicable, a “User” of your Account). If you are an individual, then you may use and access the Platform, Content, and Services through your Account as the sole User of the Account. Each user identification and password for your Account (each, “Account ID”) is personal in nature and may be used only by you or, as applicable, the User to whom the Account ID is issued.
                <br /><br />
                5.2.         Registration Information. In connection with establishing an Account, you will be asked to submit certain information about yourself and, as applicable, your organization (“Registration Information”). You agree that: (a) all such information you provide will be accurate, complete, and current; (b) you will maintain and promptly update all such information to keep it accurate, complete, and current; and (c) you will not provide any information belonging to another person or organization with the intent to impersonate that person or organization.  Before posting any Registration Information of Users associated with your Account, you are responsible for obtaining any and all authorizations required by federal or state law to authorize the sharing of their Registration Information, including their personal information, on the Platform. Propel is not liable for any invasion of privacy or other claim that may be asserted by Users of your Account as a result of your posting of Registration Information regarding Users of your Account on the Platform and the subsequent sharing of that information with other Users as described in the Privacy Policy. By providing Registration Information, you authorize Propel to disclose such information as described in the Privacy Policy.
                <br /><br />
                5.3.         Responsibilities. You are solely responsible for all access to and use of your Account (whether authorized or unauthorized), including all Content and Services accessed through your Account. Propel may deem any actions taken through your Account to have been authorized by you. You are responsible for compliance, and the compliance any other Users of your Account, with this Terms of Use. You will ensure the security and confidentiality of each Account ID and will notify Propel immediately if any Account ID is lost, stolen, or otherwise compromised. You acknowledge that you are fully responsible for all costs, fees, liabilities, or damages incurred, and material transferred, stored, modified, or shared through the use of each Account ID (whether lawful or unlawful). You acknowledge that any orders made, or other transactions completed through your Account will be deemed to have been lawfully completed by you. In no event will Propel be liable for the foregoing obligations or the failure by you to fulfill such obligations.
                <br /><br />
                5.4.         Account Authority. If you are an organization, then the individual who establishes your Account (the “Account Authority”) will have control over your Account. If you are an individual, then you will be the Account Authority for your Account, unless you designate a different Account Authority as specified below. Propel may deem the Account Authority to have full authority for all decisions relating to your Account, including: (a) addition or removal of Users; (b) permissions to access your Account; (c) disputes regarding your Account; (d) notices and other communications relating to your Account; and (e) any other decisions that may be required regarding your Account. There must be one and only one Account Authority for each Account at all times. The initial Account Authority must be designated in the initial request to establish an Account. If an initial Account Authority is not designated, the individual requesting to establish an Account shall be deemed the initial Account Authority for that Account. The Account Authority may be changed: (i) by an email sent to Propel from the registered email address of the current Account Authority; (ii) by bona fide legal written notice provided to Propel by one of your corporate officers; or (iii) as separately directed and acknowledged by Propel. It is your responsibility to properly designate a new Account Authority whenever appropriate. In the event of a dispute where multiple persons claim to be the rightful Account Authority, Propel reserves the right, at its sole discretion, to: (1) suspend all access to your Account until an Account Authority is properly designated to Propel’s sole satisfaction; or (2) terminate your Account and delete your Registration Information.
                <br /><br />
                <br />
                6.              YOUR CONTENT.   You are solely responsible for all data, ideas, submissions, questions, reviews, comments, and other content (including, text, audio, video, photographs, illustrations, graphics, testimonials, and other media) that you provide or generate through your access and use of the Platform or any Content or Services (collectively, “Your Content”). As between you and Propel, you retain ownership of Your Content. However, subject to any limitations included in the Privacy Policy, you grant Propel and its service providers a worldwide, nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable (including, to Users and other third parties) right to use, copy, sell, store, reproduce, modify, display, adapt, publish, translate, create derivative works from, and distribute (“Use”) Your Content in any for or format for purposes of operating the Platform or for any other lawful business purpose of Propel. Additionally, when you post Your Content to the Platform, you also grant Propel the right to use your name, or otherwise identify you, in connection with Your Content. You represent and warrant that none of Your Content or the Use of Your Content by Propel: (1) violates this Terms of Use, the Privacy Policy, or any applicable laws, rules, or regulations (“Laws”); (2) is libelous, defamatory, obscene, abusive, pornographic, threatening, or an invasion of privacy; (3) constitutes an infringement, misappropriation, or violation of the IPR or other rights of any third party; (4) is illegal in any way or advocates illegal activity; (5) is an advertisement or solicitation of goods or services (unless you have entered into a separate advertiser agreement with Propel); (6) is false, misleading or inaccurate; or (7) is or could be considered junk mail, spam, a part of a pyramid scheme, a disruptive commercial message or disruptive advertisement. Propel is not responsible or liable for any deletion, correction, destruction, damage, loss or failure to store, restore or back-up any of Your Content. You agree that you have all right, title, interest, and consent in Your Content necessary to allow Propel and its service providers to Use Your Content as set forth in this Terms of Use.
                <br /><br />
                <br />
                7.              ACCESS.
                <br /><br />
                7.1.          To the Platform and Services. Subject to your compliance with this Terms of Use, Propel will permit you to access and use the Platform and Services solely you’re your own lawful purposes and only in accordance with this Terms of Use and any other agreement you agree to with Propel before being given access to any specific aspects of the Platform. Any additional agreement is in addition to this Terms of Use and will govern your use of the portions of the Platform to which the additional agreement applies in the event of a conflict between the terms of this Terms of Use and the additional agreement.
                <br /><br />
                7.2.         To Content. Unless otherwise noted on the Platform, all Content available through the Platform, including all text, audio, video, photographs, illustrations, graphics, testimonials, and other media, is owned by Propel, Propel’s third-party providers, or by other Users of the Platform. All Content is provided for informational purposes only and you are solely responsible for verifying the accuracy, completeness, and applicability of all Content and for your use of any Content. Subject to your compliance with this Terms of Use, you may access the Content solely for your own personal and noncommercial purposes in connection with your own use of the Platform and Services. You will not and will not permit any third party to: (a) alter, modify, reproduce, or create derivative works of any Content; (b) distribute, sell, resell, lend, loan, lease, license, sublicense, or transfer any Content; or (c) alter, obscure, or remove any copyright, trademark, or any other notices that are provided on or in connection with any Content. Propel has not verified the accuracy of and will not be responsible for any errors or omissions in any Content. Propel makes no guarantees regarding the accuracy, currency, suitability, or quality of any Content. Without limiting the foregoing, Propel will not be held liable to you or any other third party for any Content, including Your Content under a Federal Law the Communications Decency Act or CDA, 47 U.S.C. § 230. Except as set forth in this Terms of Use, you are granted no licenses or other rights in or to any Content, or any IPR therein or related thereto. If you would like to use any Content in a manner not permitted by this Terms of Use, please contact Propel.
                <br /><br />
                7.3.         To Other Users.  The Platform may allow you to link, connect, or otherwise communicate with other Users through the Platform. By linking, connecting, or communicating with other Users, you are agreeing to allow those Users to communicate directly with you through the Platform. You agree that you are solely responsible for all communications between you and any other User through the Platform. Your extension or acceptance of a link, connection, or other communication with another User will serve as your affirmative “opt in” to the disclosure of any of Your Content or other data or information (which may include your personal information) that you provide to that other User.
                <br /><br />
                7.4.         To Propel Events.  You may be permitted to attend certain events hosted by Propel on behalf of a third party, which may be a client of Propel (“Propel Events”). In order to host such Propel Events, Propel may receive certain personal information about you from its clients and other third parties. Propel may use such information combined with the Registration Information from your Account for any business purpose related to Propel Events. Your submission of such information to Propel will serve as your affirmative “opt in” to the disclosure of such information to Propel’s clients, vendors, service providers, and exhibitors related to such Propel Events.
                <br /><br />
                7.5.         To Third-Party Services. The Platform may provide you with access to certain Services developed, provided, or maintained by other third-party service providers ("Third Party Services"). In addition to the terms of this Terms of Use, your access to and use of any Third-Party Services is also subject to any other agreement you may agree to before being given access to the Third-Party Services (each, a "Third Party Service Agreement"). The terms of any Third-Party Service Agreement (which may include payment of fees) will apply to the applicable Third-Party Services provided under that Third Party Service Agreement in addition to the terms of this Terms of Use, but will not apply to any other Services you may access through the Platform. Except as set forth in this Terms of Use, the terms of any Third-Party Service Agreement will control in the event of a conflict between the terms of this Terms of Use and that Third Party Service Agreement.
                <br /><br />
                7.6.         To Social Media Features.  The Platform may provide certain social media features that enable you to link certain Content available on the Platform to third-party social media sites or cause limited portions of Content available on the Platform to appear on third-party social media sites. You may use these social media features only as they are provided by Propel, solely with respect to the Content as it is displayed on the Platform, and otherwise in accordance with any additional terms and conditions provided by Propel with respect to such social media feature. Propel may disable all or any social media features and any links at any time without notice in Propel’s sole discretion.
                <br /><br />
                <br />
                8.              ORDERS AND TERMS OF SALE.  You may be permitted to place orders seeking to purchase a products and other offering from Propel (“Propel Offering”) available for sale on the Platform (whether in the form of an online order submitted through the Platform or an order submitted by way of email, phone, or other form permitted by Propel, an “Order”). All Orders are subject acceptance by Propel, in its sole discretion. In addition to this Terms of Use, your purchase of any Propel Offering is governed by the terms displayed on the Platform in connection with each Propel Offering and any additional terms provided to you in connection with your Order or any acceptance of your Order provided by Propel (the “Terms of Sale”). By placing an Order, you agree to be bound by the Terms of Sale with respect to that Order and any Propel Offering included in that Order. If this Terms of Use conflicts with the Terms of Sale for any Order, the Terms of Sale will govern and control with respect to the Propel Offering provided to you under that Order.  Risk of loss and title to any Propel Offering you purchase pass to you upon delivery of such Propel Offering to the applicable carrier. If a Propel Offering is listed at an incorrect price or with incorrect information, Propel shall have the right to refuse or cancel any Order placed for such Propel Offering, whether or not the Order has been confirmed or your credit card has been charged. If your credit card has already been charged for an Order and your Order is canceled, Propel will promptly issue you a credit in the amount of the charge.
                <br /><br />
                <br />
                9.           TERMINATION. You may cease use of the Platform at any time. If you also wish to disable access to your Account and terminate this Terms of Use, you may contact Propel as indicted on the Platform to request that your Account be disabled. Propel may terminate this Terms of Use at any time in its sole discretion by disabling access to your Account or by providing notice to you. Upon any termination of this Terms of Use: (1) all rights granted to you under this Terms of Use will terminate; (2) you will immediately cease all use of and access to the Platform and all Content and Services; (3) you will cease use of and delete all Content you obtained prior to termination; and (4) Propel may, in its sole discretion, disable your Account and delete any of Your Content. Propel may, in its sole discretion, fulfil any Orders pending at the time of any termination of this Terms of Use or cancel any pending Orders and refund any pre-paid amounts. Sections 1 (Definitions), 6 (Your Content), 9 (Orders and Terms of Sale), 10 (Termination), 11 (Suspension), 12 (Platform Technology), 13 (Ownership), 14 (Propel Marks), 15 (Representations and Warranties), 16 (Indemnity), 17 (Limitation on Liability), 18 (Data Privacy), 19 (Feedback), 20 (Claims of Infringement), 21 (Governing Law and Venue), 22 (Notices), 23 (International Access), 24 (Linked Sites), and 25 (Additional Terms) will survive any expiration or termination of this Terms of Use.
                <br /><br />
                <br />
                10.            SUSPENSION. Without limiting Propel’s right to terminate this Terms of Use, Propel may also suspend your access to your Account, the Platform, any Content, or any Services, with or without notice to you, upon any actual, threatened, or suspected breach of this Terms of Use or applicable law or upon any other conduct deemed by Propel, in its sole discretion, to be inappropriate or detrimental to the Platform, Services, Propel, or any other User or third party.
                <br /><br />
                <br />
                11.           OWNERSHIP. The Technology, all additions, improvements, updates, and modifications thereto, and all intellectual and proprietary property rights, including all copyrights, trademarks, service marks, trade secrets, patent rights, moral rights, and rights in data and databases (“IPR”), in and to the Technology are and will remain the sole and exclusive property of Propel and its third-party providers. You receive no ownership interest in or to the Technology and you are not granted any right or license to use the Technology itself, apart from your ability to access the Platform, Content, and Services under this Terms of Use.
                <br /><br />
                <br />
                12.           PLATFORM TECHNOLOGY. The Platform, and the databases, software, hardware and other technology used by or on behalf of Propel to operate the Platform, and the structure, organization, and underlying data, information, and software code thereof (collectively, the "Technology"), constitute valuable trade secrets of Propel. You will not, and will not permit any third party to: (1) access or attempt to access the Technology except as expressly provided in this Terms and Service; (2) use the Technology in any unlawful manner or in any other manner that could damage, disable, overburden, or impair the Technology; (3) use automated scripts to collect information from or otherwise interact with the Technology; (4) alter, modify, reproduce, create derivative works of the Technology; (5) distribute, sell, resell, lend, loan, lease, license, sublicense, or transfer any of your rights to access or use the Technology or otherwise make the Technology available to any third party; (6) reverse engineer, disassemble, decompile, or otherwise attempt to derive the method of operation of the Technology; (7) attempt to circumvent or overcome any technological protection measures intended to restrict access to any portion of the Technology; (8) monitor the availability, performance, or functionality of the Technology; (9) interfere with the operation or hosting of the Technology; or (10) introduce any viruses, Trojan horses, worms, logic bombs or other material into the Platform that is harmful to the Platform or Technology.
                <br /><br />
                <br />
                13.           PROPEL MARKS. The Propel name and logo, and all names and logos displayed on the Platform, through the Services, or in any Content, are trademarks or service marks of Propel and its subsidiaries, divisions, and third-party providers. You are granted no right or license to use any such trademarks or service marks. Any use of such trademarks or service marks without Propel’s express written consent is strictly prohibited.
                <br /><br />
                <br />
                14.           REPRESENTATIONS AND WARRANTIES.
                <br /><br />
                14.1.        Mutual. Each party hereby represents and warrants to the other party that: (a) it has the legal right and authority to enter into this Terms of Use; (b) this Terms of Use forms a binding legal obligation on behalf of such party; and (c) it has the legal right and authority to perform its obligations under this Terms of Use and to grant the rights and licenses described in this Terms of Use.
                <br /><br />
                14.2.       Compliance with Laws. You acknowledge that the Platform is a general purpose online service and is not specifically designed to facilitate compliance with any specific Law. You represent and warrant to Propel that your use of and access to the Platform or any Content or Services, will comply with all applicable Laws and will not cause Propel itself or any other third party to violate any applicable Laws. Propel is not responsible for notifying you of any such Laws, enabling your compliance with any such Laws, or for your failure to comply with any such Laws.
                <br /><br />
                14.3.       No Warranties; Disclaimer. THE PLATFORM, CONTENT, AND SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT ANY WARRANTIES, WHETHER EXPRESS OR IMPLIED. PROPEL AND ITS SERVICE PROVIDERS DO NOT WARRANT OR GUARANTEE THE ACCURACY, COMPLETENESS, ADEQUACY, OR CURRENCY OF THE PLATFORM OR ANY CONTENT OR SERVICES, INCLUDING ANY PRODUCT INFORMATION DISPLAYED ON THE PLATFORM. PROPEL DOES NOT ENDORSE ANY PRODUCTS OR ANY VIEWS OR OPINIONS THAT MAY BE EXPRESSED IN THE CONTENT OR OTHERWISE PROVIDED THROUGH THE PLATFORM. PROPEL AND ITS SERVICE PROVIDERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND REPRESENTATIONS OF ANY KIND WITH REGARD TO THE PLATFORM AND ALL CONTENT AND SERVICES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, TITLE, COMPLETENESS, ACCURACY, OR NON-INFRINGEMENT. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY PROPEL, ITS EMPLOYEES, OR SERVICE PROVIDERS WILL INCREASE THE SCOPE OF, OR CREATE ANY WARRANTIES IN ADDITION TO THE WARRANTIES EXPRESSLY SET FORTH IN THIS TERMS OF USE.
                <br /><br />
                PROPEL AND ITS SERVICE PROVIDERS MAKE NO WARRANTY THAT (a) THE PLATFORM WILL MEET YOUR REQUIREMENTS; (b) THE PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (c) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE PLATFORM WILL BE ACCURATE OR RELIABLE; (d) THE QUALITY OF ANY CONTENT OR SERVICES OBTAINED THROUGH THE PLATFORM WILL MEET YOUR EXPECTATIONS; (e) THE PLATFORM WILL NOT INCLUDE ANY TYPOGRAPHICAL OR OTHER ERRORS; OR (f) ANY ERRORS IN THE PLATFORM
                <br /><br />
                WILL BE ACCURATE OR RELIABLE; (d) THE QUALITY OF ANY CONTENT OR SERVICES OBTAINED THROUGH THE PLATFORM WILL MEET YOUR EXPECTATIONS; (e) THE PLATFORM WILL NOT INCLUDE ANY TYPOGRAPHICAL OR OTHER ERRORS; OR (f) ANY ERRORS IN THE PLATFORM WILL BE CORRECTED. ANY CONTENT OR SERVICES OBTAINED THROUGH THE USE OF THE PLATFORM IS OBTAINED AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.
                <br /><br />
                <br />
                15.           INDEMNITY. You hereby agree to indemnify, defend, and hold harmless Propel and its subsidiaries, divisions, affiliates, officers, directors, shareholders, employees, agents, service providers, contractors, assigns, users, clients, providers, licensees, and successors in interest ("Indemnified Parties") from any and all claims, losses, liabilities, damages, fees, expenses and costs (including attorneys’ fees, court costs, damage awards, and settlement amounts) that result from any claim or allegation (“Claim”) against any Indemnified Party arising in any manner from: (1) your access to or use of the Platform or any Content or Services; (2) Your Content, or any other information or data you Provide to Propel; (3) your violation of applicable Laws; and (4) your breach of any provision of this Terms of Use. Propel will use reasonable efforts to provide you with notice of any such claim or allegation, and Propel will have the right to participate in the defense of any such claim at its expense.
                <br /><br />
                <br />
                16.           LIMITATION ON LIABILITY. PROPEL AND ITS SUBSIDIARIES, DIVISIONS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, HOWEVER CAUSED, UNDER ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE), ARISING IN CONNECTION WITH OR OUT OF THE ACCESS TO OR USE OF THE PLATFORM OR ANY CONTENT OR SERVICES, EVEN IF PROPEL AND ITS SUBSIDIARIES, DIVISIONS, AND SERVICE PROVIDERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING, WITHOUT LIMITATION, ANY LOSS OF YOUR CONTENT, OPPORTUNITY, REVENUES, PROFITS OR REPUTATION, BUSINESS INTERRUPTION, OR PROCUREMENT OF SUBSTITUTE CONTENT, GOODS OR SERVICES. THE TOTAL CUMULATIVE LIABILITY OF PROPEL
                <br /><br />
                <br />
                AND ITS SUBSIDIARIES, DIVISIONS, AND SERVICE PROVIDERS IN CONNECTION WITH THIS TERMS OF USE, THE PLATFORM AND ALL CONTENT AND SERVICES, OR ANY PRODUCTS PROVIDED UNDER THIS TERMS OF USE OR THROUGH THE PLATFORM, WHETHER IN CONTRACT OR TORT OR OTHERWISE, WILL NOT EXCEED THE GREATER OF $100, OR THE AMOUNTS PAID BY YOU RESULTING FROM ANY ORDERS MADE IN THE MONTH IMMEDIATELY PRECEDING THE ACT GIVING RISE TO SUCH LIABILITY. YOU AGREE THAT PROPEL WOULD NOT ENTER INTO THIS TERMS OF USE WITHOUT THESE LIMITATIONS ON ITS LIABILITY. IN JURISDICTIONS WHERE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES IS NOT PERMITTED, THE LIABILITY OF PROPEL AND ITS SUBSIDIARIES, DIVISIONS, AND SERVICE PROVIDERS IS LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
                <br /><br />
                <br />
                17.           DATA PRIVACY. You agree to comply with the Privacy Policy posted on the Platform (the “Privacy Policy”). You expressly consent to the use and disclosure of your personal information and other data and information as described in the Privacy Policy (https://www.propelem.com/legal). Notwithstanding anything in the Privacy Policy, Propel will have the right to collect, extract, compile, synthesize, and analyze non-personally identifiable data or information (data or information that does not identify an entity or natural person as the source thereof) resulting from your access to and use of the Platform or any Services or Content. To the extent any such non-personally identifiable data or information is collected or generated by Propel, the data and information will be solely owned by Propel and may be used by Propel for any lawful business purpose without a duty of accounting to you, provided that the data and information is used only in an aggregated form, without directly identifying you or any other entity or natural person as the source thereof.
                <br /><br />
                <br />
                18.           FEEDBACK. If you provide Propel any feedback or suggestions regarding the Platform or any Content or Services (“Feedback”), you herby assign to Propel all rights in the Feedback and agree that Propel shall have the right to use such Feedback and related information in any manner it deems appropriate without a duty of accounting to you. Propel will treat any Feedback you provide to Propel as non-confidential and non-proprietary. You agree that you will not submit to Propel any information or ideas that you consider to be confidential or proprietary.
                <br /><br />
                <br />
                19.           CLAIMS OF INFRINGEMENT. Propel respects your copyrights and other intellectual property rights and those of other third parties. If you believe in good faith that your copyrighted work has been reproduced on the Platform without your authorization in a way that constitutes copyright infringement, you may notify our designated copyright agent by mail to:
                <br /><br />
                Attn: Legal
                Propel  INC
                4540 Campus Drive, Suite 500
                Newport Beach, CA 92660 USA
                <br /><br />
                Email: office @ Propelem.com
                <br /><br />
                Please provide the following information to the Propel Copyright Agent: (1) the identity of the allegedly infringing work; (2) your name, address, daytime phone number, and email address, if available; (3) a statement that you have a good-faith belief that the use of the copyrighted work is not authorized by the owner, his or her agent, or the law; (4) a statement that the information in the notification is accurate and, under penalty of perjury, that you are authorized to act on behalf of the owner; and (5) your electronic or physical signature. Propel will take whatever action, in its sole discretion, it deems appropriate, including the removing the allegedly infringing work from the Platform.
                <br /><br />
                <br />
                20.           GOVERNING LAW AND VENUE. The interpretation of the rights and obligations of the parties under this Terms of Use, including, to the extent applicable, any negotiations, arbitrations, or other proceedings hereunder, will be governed in all respects exclusively by the laws of the State of California, U.S.A., as such laws apply to contracts between residents of Missouri without regard to conflict of law’s provisions thereof. Each party will bring any action or proceeding arising from or relating to this Terms of Use exclusively in a federal or state court in n Santa Ana, California, U.S.A., and you irrevocably submit to the personal jurisdiction and venue of any such courts in any such action or proceeding brought in such courts by Propel.
                <br /><br />
                <br />
                21.           NOTICES. Unless otherwise specified in this Terms of Use, any notices required or allowed under this Terms of Use will be provided to Propel by postal mail to the address for Propel listed on the Platform. Propel may provide you with any notices required or allowed under this Terms of Use by sending you an email to any email address you provide to Propel, provided that in the case of any notice applicable both to you and other Users of the Platform, Propel may instead provide such notice by posting on the Platform. Notices provided to Propel will be deemed given when actually received by Propel. Notice provided to you will be deemed given 24 hours after posting to the Platform or sending via e-mail, unless (as to e-mail) the sending party is notified that the e-mail address is invalid.
                <br /><br />
                <br />
                22.           INTERNATIONAL ACCESS. The Platform may be accessed from countries other than the U.S.A. The Platform may contain Propel Offerings or references to Propel Offerings that are not available outside of the U.S.A. Any such references do not imply that such products will be made available outside the U.S.A. If you access and use this Platform outside the U.S.A., you are responsible for complying with your local Laws in addition to any requirements outlined in this Terms of Use.
                <br /><br />
                <br />
                23.           LINKED SITES. The Platform or any Content or Services may contain links to third-party Platforms or content that are not under the control of Propel. If you access a third-party sites or content from the Platform or any Content Services, then you do so at your own risk and Propel is not responsible for any content on any linked site. You may establish a link to the Platform, provided that the link does not state or imply any sponsorship or endorsement of your site by Propel. You may not frame or otherwise incorporate into another site the Content or other materials on the Platform without Propel’s prior written consent.
                <br /><br />
                <br />
                24.           ADDITIONAL TERMS. Unless otherwise amended, this Terms of Use will exclusively govern your access to and use of the Platform or any Content or Services and is the complete and exclusive understanding and agreement between the parties, and supersedes any oral or written proposal, agreement, or other communication between the parties, regarding your access to and use of the Platform or any Content or Services. Except as expressly set forth in this Terms of Use, this Terms of Use may be amended or modified only by a writing signed by both parties. You agree as it relates to our remedy at law for any actual or threatened breach of this Terms of Use that Propel shall be entitled to specific performance or injunctive relieve, or both, in addition to any damages that we may be legally entitled to recover. No right or remedy shall be exclusive of any other, whether
                <br/><br />
                at law or in equity. All waivers by Propel under this Terms of Use must be in writing or later acknowledged by Propel in writing. Any waiver or failure by Propel to enforce any provision of this Terms of Use on one occasion will not be deemed a waiver by Propel of any other provision or of such provision on any other occasion. If any provision of this Terms of Use is held to be unenforceable, that provision will be removed to the extent necessary to comply with the law, replaced by a provision that most closely approximates the original intent and economic effect of the original to the extent consistent with the law, and the remaining provisions will remain in full force. The prevailing party in any lawsuit or proceeding arising from or related to this Terms of Use will be entitled to receive its costs, expert witness fees and reasonable attorneys’ fees, including costs and fees on appeal. You agree that each of Propel’s service providers shall be considered a third-party beneficiary of the above provisions, with all rights to enforce such provisions as if a service provider were a party to this Terms of Use. Neither this Terms of Use nor any rights or obligations of you hereunder may be assigned or transferred by you (in whole or in part and including by sale, merger, consolidation, or other operation of law) without the prior written approval of Propel. Any assignment in violation of the foregoing will be null and void. Propel may assign this Terms of Use to any party that assumes Propel’s obligations hereunder. The parties hereto are independent parties, not agents, employees or employers of the other or joint venturers, and neither acquires hereunder any right or ability to bind or enter into any obligation on behalf of the other. Any reference herein to "including" will mean "including, without limitation."
                <br /><br />
                Updated: June 09, 2020
            </p>
            <NavLink to={'/'} className="text-5xl mb-4 font-light">Propel Inc.</NavLink>
            <span className="font-light text-2xl">© 2020-2023</span>

        </div>
    );
};

export default Index;